apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  template:
    spec:
      containers:
      - name: myapp
        image: myapp:latest
        env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: SECRET_KEY
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: DATABASE_USER
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: DATABASE_PASSWORD
