apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  SECRET_KEY: c2VjcmV0S2V5Cg==  # Base64 encoded value of SECRET_KEY
  DATABASE_USER: ZGF0YWJhc2VVc2VyCg==  # Base64 encoded value of DATABASE_USER
  DATABASE_PASSWORD: ZGF0YWJhc2VQYXNzd29yZAo=  # Base64 encoded value of DATABASE_PASSWORD
