spec:
  template:
    spec:
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          livenessProbe:
            { { - toYaml .Values.livenessProbe | nindent 12 } }
          readinessProbe:
            { { - toYaml .Values.readinessProbe | nindent 12 } }
          resources:
            { { - toYaml .Values.resources | nindent 12 } }
      replicas:
          {{ .Values.replicaCount }}
      strategy:
        type: RollingUpdate